### ISSUE TITLE
when can we expect fix for database warning 

### ISSUE THREAD

**Issue by anilk9096** [matrix-org/sygnal#118]
hi,
we are planning to migrate from xmpp to matrix with mobile clients . we are running sygnal as push gateway but service running not listening on 5000 port. Any alternate push gateway for matrix synapse

**Comment by babolivier** [comment]
Please use github issues for actual bug reports. The warning will be fixed in https://github.com/matrix-org/sygnal/pull/100, which is now pending on review. Also, as it's been already mentioned in https://github.com/matrix-org/sygnal/issues/109, the warning doesn't seem to be related with Sygnal not listening on port 5000, I suggest you open an issue for this separate bug and then it'll be investigated when we can look at it.
