### ISSUE TITLE
Integration with a self-hosted synapse

### ISSUE THREAD

**Issue by almereyda** [matrix-org/sygnal#13]
In the case of a self-hosted synapse server, the push gateway is configured to serve the official app.

Can I run my own sygnal next to synapse, and the Riot app autodetects my custom notification service?

A recent blog post also mentioned https://github.com/slp/matrix-pushgw

**Comment by Christilut** [comment]
Did you figure this out?

I'm running my own synapse server with a custom made javascript client and I'm trying to get push notifications working to devices that support push (android, ios, chrome). But I can't figure out how to hook up Sygnal to Synapse. I must be missing something but I'm kind of clueless how to actually use Sygnal to send notifications.

Any pointers in the right direction would be great!

**Comment by vinzenzweber** [comment]
It is actually the client who tells Synapse that it wants to be contacted via your custom Sygnal server URL. That implies that you don't have to configure anything in the Synapse or Sygnal config files upfront. The client uses the Client-Server API to tell Synapse about the Pusher. Maybe this documentation helps: https://matrix.org/docs/spec/client_server/r0.2.0.html#post-matrix-client-r0-pushers-set

**Comment by almereyda** [comment]
Does this mean we can already run our own identity service, without having to rely on mxisd?
In case of considering Docker, I guess synapse and sygnal can both share the same base image?

We currently have few issues with *having* to use `vector.im` as IS, since `riot.im` stopped accepting CORS requests from our domain at some point, probably due to missing configuration.

**Comment by dbkr** [comment]
For clarity, the push gateway is part of your mobile app deployment rather than your home server deployment: each mobile app publishers has their own which has the APNS/GCM private keys for their apps, so it can only use the one that has the relevant private key (@vinzenzweber correctly describes how this works).

@almereyda we should take this somewhere else rather than fill this thread with chat about a different service, but I'd be interested to know which endpoints CORS isn't working on - this doesn't sound intentional. Come chat in #matrix-identity:matrix.org?

**Comment by almereyda** [comment]
I didn't know that channel; joining.

**Comment by richvdh** [comment]
sounds like this was a misunderstanding

**Comment by mrtshoot** [comment]
please visit my own sygnal push gateway with docker on https://github.com/mrtshoot/docker-sygnal
