### ISSUE TITLE
Better documentation for use cases

### ISSUE THREAD

**Issue by smoebody** [matrix-org/sygnal#160]
As i found this program i thought finally one is able to send push notifications to the element-app from ones own homeserver. Unfortunately this seems not to be the case.

Can you explain better what this program is for? Is there a way to use it in order to send push notifications to the element app?

Thanks in advance.
cheers

**Comment by anoadragon453** [comment]
This program is an implementation of a Matrix push gateway. It sits between a Matrix homeserver and a push service such as Apple APNs or Google FCM.

The README has [some links](https://github.com/matrix-org/sygnal#introduction) to more information on how everything fits together. Otherwise you can always jump into [the matrix room](https://matrix.to/#/#sygnal:matrix.org) and have a chat :)
