### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by Sr-Preet** [matrix-org/sygnal#166]
I've looking for the solution for this for almost two weeks now and still unable to rectify this problem.
We're using self hosted synapse with sygnal and constantly getting the following errors:

` File "/usr/lib/python3.8/ssl.py", line 944, in do_handshake`
`    self._sslobj.do_handshake()`
`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)
`

`sygnal.exceptions.TemporaryNotificationDispatchException: aioapns Connection Failure`
`2021-02-08 18:42:40,629 [13257] ERROR aioapns Could not connect to server: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)`

It was working fine and then suddenly it stopped on all four deployments.
Please help me.

**Comment by reivilibre** [comment]
Please would you be able to indicate whether you have tried any of the solutions suggested by us in the Sygnal room?

**Comment by Sr-Preet** [comment]
@reivilibre 
I did visit the sygnal room, but found it empty, there was no mesage or solution of any sort.
I've been through the solution suggested in sygnal githhub repo but none of them worked
Can you please help me regarding this.

**Comment by reivilibre** [comment]
I'm somewhat at a loss why you believe the room was empty, especially after having replied to our messages, but in any case, I will reproduce the information here:

This error is likely to mean that your system isn't accepting the certificate presented by Apple.

Apple's certificate is signed by the CA certificate 'GeoTrust Global CA' (we have a copy [here](https://github.com/matrix-org/sygnal/blob/master/docker/GeoTrust_Global_CA.crt), you can also download it from https://www.geotrust.com/resources/root-certificates/).

Normally you would not need to do this, but if you are using Debian (or another Linux distribution that is derived from it), you will note that this certificate was removed from the default set CA certificates (see [Debian bug 962596](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962596).

Since the Sygnal Dockerfile was also impacted, you can see the steps needed here, encoded in Dockerfile talk: https://github.com/matrix-org/sygnal/blob/ab87ab821159e4a0c8d2c55aa8dfcc0b1200a341/docker/Dockerfile#L39-L41

This could be expressed as:

> Copy GeoTrust_Global_CA.crt to /usr/local/share/ca-certificates/GeoTrust_Global_CA.crt
> Then run `update-ca-certificates`

Please be aware of what the security ramifications, of adding a CA certificate to your trust store, are.

If you are not running Debian, then please tell us at least what your environment is.

**Comment by Sr-Preet** [comment]
@reivilibre 
Thank you so much, It worked like a charm, thanks really.

**Comment by richvdh** [comment]
dup https://github.com/matrix-org/sygnal/issues/140
