### ISSUE TITLE
Development dependencies should be available as extras

### ISSUE THREAD

**Issue by callahad** [matrix-org/sygnal#190]
Right now our docs ask people to manually install tools like `tox`, `black`, and `flake8`

Instead, we should be able to install these automatically through our setup.py

Inside setup.py, in addition to the `install_requires` line, we should have an `extras_require` block like:

```
extras_require: {
    'dev': [
        'black',
        'tox',
    ]
}
```

and so on.

Then the CONTRIBUTING docs could be changed to just `pip install -e '.[dev]'` to get Sygnal _and_ its development dependencies.

**Comment by clokep** [comment]
Not 100% related but we should also bump these to the same versions we use in Synapse (black, mypy, and mypy-zope all seem to be behind, maybe isort too). We also install a couple of additional flake8 plug-ins in Synapse that could be worthwhile / the configs might be worth a sync.

If we're going to bump black we should ensure that's a separate PR since the autoformatting shouldn't be mixed with manual changes.
