### ISSUE TITLE
Apps with same bundle id

### ISSUE THREAD

**Issue by timabilov** [matrix-org/sygnal#300]
**Describe the bug**
`sygnal.yaml` - I cannot use two apps with same bundle id both ios and android

**Comment by squahtx** [comment]
Android and iOS app ids have to be different, otherwise Sygnal wouldn't be able to determine whether to send a notification to GCM or Apple.

Note that app ids in the Sygnal config are not the same as bundle ids. Apps are free to use arbitrary app ids when creating pushers via https://spec.matrix.org/v1.2/client-server-api/#post_matrixclientv3pushersset. The only thing that matters is that Sygnal is configured with the same app id that the app created the pusher with.
