### ISSUE TITLE
Synapse and Sygnal: /_matrix/push/v1/notify 404 error

### ISSUE THREAD

**Issue by iphost** [matrix-org/sygnal#31]
Hello. I am trying to setup synapse and sygnal on the same server. The setup seems to work well except the push notifications part. More specifically - when I send a message, synapse receives it and attempts to communicate with sygnal - but fails with the following error:

2019-02-23 12:25:49,397 - synapse.http.client - 96 - INFO - httppush.process-398- Sending request POST https://myhostname.com/_matrix/push/v1/notify
2019-02-23 12:25:49,411 - synapse.metrics - 374 - INFO - - Collecting gc 0
2019-02-23 12:25:49,415 - synapse.access.http.8008 - 233 - INFO - POST-45257- ::ffff:127.0.0.1 - 8008 - Received request: POST /_matrix/push/v1/notify
2019-02-23 12:25:49,416 - synapse.access.http.8008 - 302 - INFO - POST-45257- ::ffff:127.0.0.1 - 8008 - {None} Processed request: 0.001sec/-0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 167B 404 "POST /_matrix/push/v1/notify HTTP/1.0" "Synapse/0.34.0.1" [0 dbevts]
2019-02-23 12:25:49,418 - synapse.http.client - 111 - INFO - httppush.process-398- Received response to  POST https://myhostname.com/_matrix/push/v1/notify: 404
2019-02-23 12:25:49,419 - synapse.push.httppusher - 339 - WARNING - httppush.process-398- Failed to push event 

What am I doing wrong?

**Comment by evilham** [comment]
You should likely proxy `/_matrix/push/` to wherever your sygnal instance is listening on (UNIX socket, TCP port, ...), this depends on your gunicorn settings if that's what you are using.

**Comment by whigger85** [comment]
I have the same problem. I have a reverse proxy in place, but the error occurs even if I call the push gateway on the same host via 127.0.0.1. Unfortunately the sygnal log only show that the 404 error was returned without further information about the reason...

Tried the command "curl --header 'Host: <hostname>' <sygnalip>:<sygnalport>/_matrix/push"
It yields the following output:

<html> <head><title>405 - Method Not Allowed</title></head> <body> <h1>Method Not Allowed</h1> <p>Your browser approached me (at /_matrix/push) with the method "GET". I only allow the method HEAD here.</p> </body> </html>

If I try to call curl with the "-I" or "--head" option to make a HEAD request, I get this:

ubuntu@chat-server:~/sygnal$ curl -I 127.0.0.1:5000/_matrix/push
HTTP/1.1 500 Internal Server Error
Server: TwistedWeb/19.7.0
Date: Sun, 20 Oct 2019 19:19:24 GMT
Content-Type: text/html
Content-Length: 95

And the sygnal.log file shows this:
2019-10-20 19:19:24,375 [4553] CRITICAL twisted
Traceback (most recent call last):
File "/home/ubuntu/.local/lib/python3.7/site-packages/twisted/web/server.py", line 217, in process
self.render(resrc)
File "/home/ubuntu/.local/lib/python3.7/site-packages/twisted/web/server.py", line 284, in render
body = resrc.render(self)
File "/home/ubuntu/.local/lib/python3.7/site-packages/twisted/web/resource.py", line 265, in render
return m(request)
File "/home/ubuntu/.local/lib/python3.7/site-packages/twisted/web/resource.py", line 275, in render_HEAD
return self.render_GET(request)
AttributeError: 'Resource' object has no attribute 'render_GET'
2019-10-20 19:19:24,376 [4553] INFO sygnal.access "-" - - [13/Jan/1970:08:16:11 +0000] "HEAD /_matrix/push HTTP/1.1" 500 - "-" "curl/7.58.0"

**Comment by evilham** [comment]
Hey, @whigger85: this is also likely an issue with the way you are proxying Sygnal.

It'd be useful to know what your Sygnal config is (mind the secrets) and also how you are proxying it, aka your nginx / apache / whatever configuration or are you using twisted itself?
It's a bit awkward because Sygnal doesn't use twisted, yet that's the kind of traceback you are showing here.

**Comment by whigger85** [comment]
Hi, thanks for the quick reply. The sygnal config is attached. I'm using nginx with the followning entry in the related file in the "sites-available" folder:

    location /pushgateway {
      proxy_pass http://127.0.0.1:5000;
      proxy_set_header X-Forwarded-For $remote_addr;
    }

Concerning twisted: I'm a little bit confused, because it seems to be an internal dependency of Sygnal. At least I don't use it explicitly. I just installed sygnal from the repo with "pip3 installl" and then started it with "python -m sygnal.sygnal". All the twisted-related output is coming from the started process.

**Comment by whigger85** [comment]
Had to update the config file ending, as yaml is apparently not supported by github.
[sygnal.txt](https://github.com/matrix-org/sygnal/files/3750410/sygnal.txt)

**Comment by richvdh** [comment]
this is a problem with the configuration of the reverse-proxy, not a sygnal bug.

**Comment by whigger85** [comment]
> this is a problem with the configuration of the reverse-proxy, not a sygnal bug.

Why do you think that this is a reverse proxy configuration error? It even occurs when I access the server from localhost (effectively bypassing reverse proxy configuration) and even if I don't have a reverse proxy configuration for the sygnal port at all.

**Comment by richvdh** [comment]
the [logs](https://github.com/matrix-org/sygnal/issues/31#issue-413688491) show that the `/_matrix/push/v1/notify` request is arriving at synapse rather than sygnal; one way or another that means that the request is being routed to the wrong place and it's not a sygnal problem.

**Comment by whigger85** [comment]
> the [logs](https://github.com/matrix-org/sygnal/issues/31#issue-413688491) show that the `/_matrix/push/v1/notify` request is arriving at synapse rather than sygnal; one way or another that means that the request is being routed to the wrong place and it's not a sygnal problem.

The first post comes from the issue creator and not from me. This is not my log output! I explicitly call the following on the sygnal host:

curl -X POST http://127.0.0.1:5000/pushgateway/_matrix/push/v1/notify -H "Content-Type: application/json" --data @test.json

And get the following result:
<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>No such child resource.</p>
  </body>
</html>

How can this be a proxy problem?

**Comment by richvdh** [comment]
you [said](https://github.com/matrix-org/sygnal/issues/31#issuecomment-544290780) "I have the same problem". If you think your problem is different, you should open a different issue.

sydent will look for `/_matrix/push/v1/notify`, not `/pushgateway/_matrix/push/v1/notify`.

**Comment by whigger85** [comment]
Hey, sorry, I have to appologize. I found the problem. It was indeed an error in the nginx configuration. The errors of localhost requests were thrown, because I accidentally added the "pushgateway" path segment in the URL. I wanted to forward requests with the location "pushgateway" (e. g. https://myserver.com/pushgateway/_matrix/push/v1/notify) to the sygnal server, but the word "pushgateway" was not replaced by nginx. The actual nginx configuration needs to be defined as following for this to work:

location /pushgateway/ {
    proxy_pass http://127.0.0.1:5000/;
}

Note the both slashes around "pushgateway" and the trailing slash after "5000". Maybe this helps other people that run into the same problem and come across this issue.
