### ISSUE TITLE
Consider migrating to FCM HTTP v1 API [old API shutoff: June 2024]

### ISSUE THREAD

**Issue by ilya-korotya** [matrix-org/sygnal#313]
**Is your feature request related to a problem? Please describe.**
FCM asks to stop using legacy authorization and switch to OAuth 2.0 https://firebase.google.com/docs/cloud-messaging/auth-server. But it looks like sygnal only supports authorization via `Authorization:key=AIzaSyZ-1u...0GBYzPu7Udno5aA` which is the old approach.

**Describe the solution you'd like**
Add a field to the config that will determine what type of authorization I want to use. Legacy or OAuth 2.0.

**Additional context**
![image](https://user-images.githubusercontent.com/20016700/177764775-9a2773c5-2121-4cda-a80c-4bc618272c61.png)

**Comment by ilya-korotya** [comment]
Using a legacy API key is now allowed, but not recommended. I think FCM may stop supporting legacy API key at any time.

**Comment by H-Shay** [comment]
The issue here is that AFAICT Sygnal currently uses the legacy HTTP API https://github.com/matrix-org/sygnal/blob/cac851bc8d750d94bb55d5e152e97c2caf2d8a9f/sygnal/gcmpushkin.py#L72, which doesn't support Oauth token authorization. We probably need to consider migrating to the HTTP v1 API although I don't see any concrete info in the docs relating to a sunset date for the legacy API.

**Comment by rltas** [comment]
The readme says "server key" but since the parameter is called "api_key" it still took us some time to realize that we explicitly have to enable the "Cloud Messaging API (Legacy)" and use that. If this migration isn't something that can easily be done, maybe just be a bit clearer/explicit about that.

**Comment by popperwin** [comment]
> We probably need to consider migrating to the HTTP v1 API although I don't see any concrete info in the docs relating to a sunset date for the legacy API.

@H-Shay 
The legacy API will be shutdown on 20 June 2024

<img width="935" alt="image" src="https://github.com/matrix-org/sygnal/assets/100386956/e00f0932-2e6b-4605-9eb6-4502d608a9d2">

**Comment by H-Shay** [comment]
> The legacy API will be shutdown on 20 June 2024
 
Thanks for the heads up!

**Comment by giomfo** [comment]
@wrjlewis FYI this is not possible to configure a FCM (Firebase Cloud Messaging) pusher for a **new** Firebase project in a Sygnal instance since June 2023.

Here is a screenshot of a new Firebase project settings in the Firebase Console:
<img width="1257" alt="Screenshot 2023-09-27 at 10 06 41" src="https://github.com/matrix-org/sygnal/assets/8969772/f542a116-ee44-4fbb-abf7-bdc5fd0c84ac">

Only FCM HTTP v1 API is allowed for a new project.

June 2024 is the deadline for the existing projects. We should migrate asap to unblock new projects

**Comment by bruno24pt** [comment]
Quick check-in about the legacy API deadline in June. Heard Element-HQ moved all the stuff over, but can't see Sygnal Pushgateway. Maybe it's still in the pipeline?

Any updates or details on this? Just trying to stay in the loop.

Thanks for any info!

**Comment by wrjlewis** [comment]
Hey 👋 

> Heard Element-HQ moved all the stuff over, but can't see Sygnal Pushgateway. Maybe it's still in the pipeline?

Yep thats correct, Sygnal will be moved over shortly. 

> Any updates or details on this? Just trying to stay in the loop.

I can't give specifics on when exactly. But we're trying to get this scheduled asap and well ahead of the API shut off date. Lack of specifics on that just due to the team's other commitments and being a smaller team.

**Comment by franzos** [comment]
This is coming in like ~3 months.
Is anyone working on this?

**Comment by giomfo** [comment]
@devonh can we consider this ticket closed by https://github.com/matrix-org/sygnal/pull/361? is there still any pending work?

**Comment by wrjlewis** [comment]
Support has been added in today's release - https://github.com/matrix-org/sygnal/releases/tag/v0.14.0

**Comment by bmarty** [comment]
FTR, this is an e-mail I have received today:

<img width="612" alt="image" src="https://github.com/matrix-org/sygnal/assets/3940906/6c6a9e50-41d3-4055-9e2e-2374a6adf6c0">

**Comment by rltas** [comment]
> We’d like to let you know that due to the high number of extension requests, we have decided to delay the shutdown time to July 20, 2024.
