### ISSUE TITLE
iOS VOIP sometimes notifications do not work if app is not open/in background

### ISSUE THREAD

**Issue by Av164** [matrix-org/sygnal#322]
iOS VOIP sometimes notifications do not work if app is not open/in background

1. Make sure sygnal is set up properly for VOIP
2. Make a VOIP call to your iOS device

Expected behavior
VOIP notifications should get triggered and the phone should ring.

 - OS: iOS 15.6

Smartphone (please complete the following information):
 - Device: iPhone 7 
 - OS: iOS 15.6

Additional context
The app I am using is built on top of Element. I can see the .voip. app ID being called in the logs whenever I call someone and I have set push type for the .voip. app IDs to 'voip'.

**Comment by reivilibre** [comment]
> I can see the .voip. app ID being called in the logs whenever I call someone and I have set push type for the .voip. app IDs to 'voip'.

Is this the Sygnal log? If so, it sounds like it may not be Sygnal's bug here?

It will likely need some research to find out which piece of software has the bug here; is it a Sygnal issue or an Element iOS issue (or possibly an issue with your custom app)?

I'm not an iOS developer and I'm afraid I'm not familiar with the restrictions. Though I believe for some aspects of notification handling that you need special consents from Apple; I don't know if this is one of those cases.

As a point of comparison, would you be able to check whether plain Element iOS from the Apple store has this problem?

**Comment by DMRobertson** [comment]
We're not easily able to investigate this. I put some links to relevant docs https://github.com/matrix-org/sygnal/issues/323#issuecomment-1259438550 which might help.

> As a point of comparison, would you be able to check whether plain Element iOS from the Apple store has this problem?

This would be very helpful to know, but otherwise I suggest you talk to the Element iOS team for advice.

**Comment by H-Shay** [comment]
Closing in favor of #323
