### ISSUE TITLE
Config checker doesn't allow for deprecated fields

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/sygnal#98]
E.g. we removed `db` as an option, which now means sygnal will not start with `db`.

We should probably make the config checker more relaxed about unknown fields.

**Comment by richvdh** [comment]
> We should probably make the config checker more relaxed about unknown fields.

but also: make the config checker understand the deprecated options?

**Comment by richvdh** [comment]
I think I misunderstood this initially. As I now understand it, the process would start and work correctly, but emit some warnings? And we want it to emit different warnings?

(relatedly: I think half the problem is that these warnings are going to the logfile. If they went to stderr then we might have noticed them during development.)
